-- VHDL module instantiation generated by SCUBA Diamond_2.0_Production (151)
-- Module  Version: 1.1
-- Mon Feb 03 17:01:33 2025

-- parameterized module component declaration
component efb_spi
    port (wb_clk_i: in  std_logic; wb_rst_i: in  std_logic; 
        wb_cyc_i: in  std_logic; wb_stb_i: in  std_logic; 
        wb_we_i: in  std_logic; 
        wb_adr_i: in  std_logic_vector(7 downto 0); 
        wb_dat_i: in  std_logic_vector(7 downto 0); 
        wb_dat_o: out  std_logic_vector(7 downto 0); 
        wb_ack_o: out  std_logic; spi_clk: inout  std_logic; 
        spi_miso: inout  std_logic; spi_mosi: inout  std_logic; 
        spi_scsn: in  std_logic; 
        spi_csn: out  std_logic_vector(0 downto 0); 
        spi_irq: out  std_logic);
end component;

-- parameterized module component instance
__ : efb_spi
    port map (wb_clk_i=>__, wb_rst_i=>__, wb_cyc_i=>__, wb_stb_i=>__, 
        wb_we_i=>__, wb_adr_i(7 downto 0)=>__, wb_dat_i(7 downto 0)=>__, 
        wb_dat_o(7 downto 0)=>__, wb_ack_o=>__, spi_clk=>__, spi_miso=>__, 
        spi_mosi=>__, spi_scsn=>__, spi_csn(0 downto 0)=>__, spi_irq=>__);
